 { 
  DTRACE_NET_SERVER_CONNECTION: [Function],
  DTRACE_NET_STREAM_END: [Function],
  DTRACE_NET_SOCKET_READ: [Function],
  DTRACE_NET_SOCKET_WRITE: [Function],
  DTRACE_HTTP_SERVER_REQUEST: [Function],
  DTRACE_HTTP_SERVER_RESPONSE: [Function],
  DTRACE_HTTP_CLIENT_REQUEST: [Function],
  DTRACE_HTTP_CLIENT_RESPONSE: [Function],
  COUNTER_NET_SERVER_CONNECTION: [Function],
  COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
  COUNTER_HTTP_SERVER_REQUEST: [Function],
  COUNTER_HTTP_SERVER_RESPONSE: [Function],
  COUNTER_HTTP_CLIENT_REQUEST: [Function],
  COUNTER_HTTP_CLIENT_RESPONSE: [Function],
  global: [Circular],
  process:
   { title: 'invisible cygwin console',
     version: 'v0.12.7',
     moduleLoadList:
      [ 'Binding contextify',
        'Binding natives',
        'NativeModule events',
        'NativeModule util',
        'NativeModule buffer',
        'Binding buffer',
        'Binding smalloc',
        'NativeModule path',
        'NativeModule module',
        'NativeModule vm',
        'NativeModule assert',
        'NativeModule fs',
        'Binding fs',
        'Binding constants',
        'NativeModule stream',
        'NativeModule _stream_readable',
        'NativeModule _stream_writable',
        'NativeModule _stream_duplex',
        'NativeModule _stream_transform',
        'NativeModule _stream_passthrough',
        'NativeModule smalloc',
        'NativeModule os',
        'Binding os',
        'NativeModule console',
        'Binding tty_wrap',
        'NativeModule net',
        'NativeModule timers',
        'Binding timer_wrap',
        'NativeModule _linklist',
        'Binding cares_wrap',
        'Binding uv',
        'Binding pipe_wrap',
        'Binding tcp_wrap',
        'Binding stream_wrap',
        'NativeModule child_process',
        'NativeModule string_decoder',
        'NativeModule dgram',
        'NativeModule constants',
        'Binding udp_wrap',
        'Binding process_wrap',
        'NativeModule zlib',
        'Binding zlib',
        'NativeModule crypto',
        'Binding crypto',
        'NativeModule tls',
        'NativeModule url',
        'NativeModule punycode',
        'NativeModule querystring',
        'NativeModule _tls_common',
        'NativeModule _tls_wrap',
        'Binding tls_wrap',
        'NativeModule _tls_legacy',
        'NativeModule dns' ],
     versions:
      { http_parser: '2.3',
        node: '0.12.7',
        v8: '3.28.71.19',
        uv: '1.6.1',
        zlib: '1.2.8',
        modules: '14',
        openssl: '1.0.1p' },
     arch: 'x64',
     platform: 'win32',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'D:\\github\\ExpressTemplate\\test\\testDb.js' ],
     execArgv: [],
     env:
      { 
        ACLOCAL_PATH: 'C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal',
        ALLUSERSPROFILE: 'C:\\ProgramData',
        APPDATA: 'C:\\Users\\15072202\\AppData\\Roaming',
        COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
        COMPUTERNAME: 'CNHQ-15072202N',
        COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
        'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
        CommonProgramW6432: 'C:\\Program Files\\Common Files',
        EXEPATH: 'C:\\Program Files\\Git',
        FP_NO_HOST_CHECK: 'NO',
        HOME: 'C:\\Users\\15072202',
        HOMEDRIVE: 'C:',
        HOMEPATH: '\\Users\\15072202',
        HOSTNAME: 'CNHQ-15072202N',
        INFOPATH: 'C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info',
        LANG: 'zh_CN.UTF-8',
        LESS_HOME: 'D:\\platform\\less.js-windows',
        LOCALAPPDATA: 'C:\\Users\\15072202\\AppData\\Local',
        LOGONSERVER: '\\\\SN-HQDC07',
        MANPATH: 'C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man',
        MSDevDir: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Common\\MSDev98',
        MSYSTEM: 'MINGW64',
        NUMBER_OF_PROCESSORS: '4',
        OLDPWD: 'D:/github/ExpressTemplate',
        OS: 'Windows_NT',
        PATH: 'C:\\Users\\15072202\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\nodejs;D:\\platform\\less.js-windows;C:\\Program Files (x86)\\SinoVoice\\jTTS 5.0 Desktop\\Bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\Common\\Tools\\WinNT;C:\\Program Files (x86)\\Microsoft Visual Studio\\Common\\MSDev98\\Bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\Common\\Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\bin;C:\\Users\\15072202\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl',
        PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        PKG_CONFIG_PATH: 'C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig',
        PLINK_PROTOCOL: 'ssh',
        PRINTER: '\\\\10.19.252.23\\l3_3F_lexmarkx656de',
        PROCESSOR_ARCHITECTURE: 'AMD64',
        PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
        PROCESSOR_LEVEL: '6',
        PROCESSOR_REVISION: '3c03',
        PROGRAMFILES: 'C:\\Program Files',
        PS1: '\\[\\033]0;$MSYSTEM:${PWD//[^[:ascii:]]/?}\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
        PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
        PUBLIC: 'C:\\Users\\Public',
        PWD: 'D:/github/ExpressTemplate/test',
        ProgramData: 'C:\\ProgramData',
        'ProgramFiles(x86)': 'C:\\Program Files (x86)',
        ProgramW6432: 'C:\\Program Files',
        SESSIONNAME: 'Console',
        SHELL: 'C:/Program Files/Git/usr/bin/bash',
        SHLVL: '1',
        SYSTEMDRIVE: 'C:',
        SYSTEMROOT: 'C:\\Windows',
        TEMP: 'C:\\Users\\15072202\\AppData\\Local\\Temp',
        TERM: 'xterm',
        TMP: 'C:\\Users\\15072202\\AppData\\Local\\Temp',
        TMPDIR: 'C:\\Users\\15072202\\AppData\\Local\\Temp',
        UATDATA: 'C:\\Windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77',
        USERDNSDOMAIN: 'SN.SUNING.AD',
        USERDOMAIN: 'SN',
        USERNAME: '15072202',
        USERPROFILE: 'C:\\Users\\15072202',
        WINDIR: 'C:\\Windows',
        _: 'C:/Program Files/nodejs/node',
        http_proxy: 'http://10.19.110.31:8080',
        http_proxy_pass: 'qwe123ZP',
        http_proxy_user: '15072202',
        include: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\atl\\include;C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\mfc\\include;C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\include',
        lib: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\mfc\\lib;C:\\Program Files (x86)\\Microsoft Visual Studio\\VC98\\lib',
        npm_home: 'C:\\Users\\15072202\\AppData\\Roaming\\npm',
        windows_tracing_flags: '3',
        windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log' 
    },
     pid: 5344,
     features:
      { debug: false,
        uv: true,
        ipv6: true,
        tls_npn: true,
        tls_sni: true,
        tls_ocsp: true,
        tls: true },
     _needImmediateCallback: false,
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     debugPort: 5858,
     _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
     _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
     _getActiveRequests: [Function: _getActiveRequests],
     _getActiveHandles: [Function: _getActiveHandles],
     reallyExit: [Function: reallyExit],
     abort: [Function: abort],
     chdir: [Function: chdir],
     cwd: [Function: cwd],
     umask: [Function: umask],
     _kill: [Function: _kill],
     _debugProcess: [Function: _debugProcess],
     _debugPause: [Function: _debugPause],
     _debugEnd: [Function: _debugEnd],
     hrtime: [Function: hrtime],
     dlopen: [Function: dlopen],
     uptime: [Function: uptime],
     memoryUsage: [Function: memoryUsage],
     binding: [Function: binding],
     _linkedBinding: [Function: _linkedBinding],
     _setupDomainUse: [Function: _setupDomainUse],
     _events: { exit: [Function] },
     _rawDebug: [Function],
     domain: null,
     _maxListeners: undefined,
     EventEmitter:
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: 10,
        init: [Function],
        listenerCount: [Function] },
     _fatalException: [Function],
     _exiting: false,
     assert: [Function],
     config: { target_defaults: [Object], variables: [Object] },
     nextTick: [Function: nextTick],
     _tickCallback: [Function: _tickCallback],
     _tickDomainCallback: [Function: _tickDomainCallback],
     stdout: [Getter],
     stderr: [Getter],
     stdin: [Getter],
     openStdin: [Function],
     exit: [Function],
     kill: [Function],
     addListener: [Function],
     on: [Function],
     removeListener: [Function],
     mainModule:
      { id: '.',
        exports: {},
        parent: null,
        filename: 'D:\\github\\ExpressTemplate\\test\\testDb.js',
        loaded: true,
        children: [Object],
        paths: [Object] },
     _immediateCallback: [Function: processImmediate] },
  GLOBAL: [Circular],
  root: [Circular],
  Buffer:
   { [Function: Buffer]
     poolSize: 8192,
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function],
     concat: [Function],
     byteLength: [Function] },
  setTimeout: [Function],
  setInterval: [Function],
  clearTimeout: [Function],
  clearInterval: [Function],
  setImmediate: [Function],
  clearImmediate: [Function],
  console: [Getter],
  logger:
   { category: 'normal',
     _events: { log: [Object] },
     level: { level: 5e-324, levelStr: 'ALL' } },
  database:
   { pool:
      { domain: null,
        _events: {},
        _maxListeners: undefined,
        config: [Object],
        _acquiringConnections: [],
        _allConnections: [Object],
        _freeConnections: [],
        _connectionQueue: [],
        _closed: false } } }